services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0
    container_name: mealie
    restart: always
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      -  /DATA/AppData/mealie/mealie:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Anchorage
      #BASE_URL: https://mealie.yourdomain.com
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - /DATA/AppData/mealie/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie
      PGUSER: mealie
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3

x-casaos:
  architectures:
    - arm64
    - amd64
    - arm
  main: mealie
  store_app_id: mealie
  author: delwinwal
  category: Notes
  description:
    en_us: A self-hosted recipe manager and meal planner with a RestAPI backend and a reactive frontend application built in Vue for a pleasant user experience for the whole family.
  developer: LangGenius
  icon: https://raw.githubusercontent.com/delwinwal/casaos-labstore/refs/heads/main/Apps/Mealie/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/delwinwal/casaos-labstore/refs/heads/main/Apps/Mealie/screenshot-1.png
  #thumbnail:
  tagline:
    en_us: A Place For All Your Recipes
  title:
    en_us: Mealie
  index: /
  port_map: "9925"
