name: ollama
services:
    ollama:
        container_name: ollama
        image: ollama/ollama
        volumes:
            - ollama:/root/.ollama
        ports:
            - 11434:11434
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
volumes:
    ollama:
        external: true
        name: ollama
